//! Vault key constants — AUTO-GENERATED by scripts/gen-vault-keys.mjs. DO NOT EDIT.
//! Single source: proto/vault-keys.json. 새 key 추가 시 본 파일 X, JSON 만 수정.
//!
//! Phase 6 정공 (2026-05-13) — 옛 manual Rust 하드코드 폐기.

pub const VK_SYSTEM_TIMEZONE: &str = "system:timezone";
pub const VK_SYSTEM_AI_MODEL: &str = "system:llm:model";
pub const VK_SYSTEM_AI_THINKING_LEVEL: &str = "system:llm:thinking-level";
pub const VK_SYSTEM_USER_PROMPT: &str = "system:user-prompt";
pub const VK_SYSTEM_AI_ASSISTANT_MODEL: &str = "system:ai-router:model";
pub const VK_SYSTEM_AI_ROUTER_ENABLED: &str = "system:ai-router:enabled";
pub const VK_LLM_ANTHROPIC_CACHE: &str = "system:llm:anthropic-cache";
pub const VK_SYSTEM_LAST_MODEL_BY_CATEGORY: &str = "system:llm:last-by-category";
pub const VK_ADMIN_ID: &str = "FIREBAT_ADMIN_ID";
pub const VK_ADMIN_PASSWORD: &str = "FIREBAT_ADMIN_PASSWORD";
pub const VK_COST_BUDGET: &str = "system:cost:budget";
pub const VK_IMAGE_MODEL: &str = "system:image-model";
pub const VK_IMAGE_SIZE: &str = "system:image-size";
pub const VK_IMAGE_QUALITY: &str = "system:image-quality";
pub const VK_SYSTEM_UI_LANG: &str = "system:ui-lang";
pub const VK_INTERNAL_MCP_TOKEN: &str = "system:internal-mcp-token";
pub const VK_INTERNAL_MCP_TOKEN_CREATED: &str = "system:internal-mcp-token-created";

pub const AUTH_SESSION_PREFIX: &str = "auth:session:";
pub const USER_SECRET_PREFIX: &str = "user:";

/// 메인 LLM 모델 미설정 시 폴백 — settings.rs get_ai_model 기본값 single source.
pub const DEFAULT_LLM_MODEL_FALLBACK: &str = "claude-sonnet-4-6";
/// 사고 수준 미설정 시 폴백 — settings.rs get_ai_thinking_level 기본값 single source.
pub const DEFAULT_THINKING_LEVEL: &str = "medium";
/// 사용자 지시사항 최대 글자 수 — settings.rs + frontend SettingsModal 공통 single source.
pub const USER_PROMPT_MAX_CHARS: usize = 2000;

/// 사용자 시크릿 key — `user:<name>` 형식. AI 가 모듈 호출 시 이 prefix 의 시크릿 자동 주입.
pub fn vk_user_secret(name: &str) -> String {
    format!("user:{}", name)
}

/// Capability 설정 key — `system:capability:<id>:settings` 형식. CapabilityManager 가 사용.
pub fn vk_capability_settings(cap_id: &str) -> String {
    format!("system:capability:{}:settings", cap_id)
}

/// Module 설정 key — `system:module:<name>:settings` 형식. ModuleManager / CapabilityManager 활성화 검사 시 사용.
pub fn vk_module_settings(name: &str) -> String {
    format!("system:module:{}:settings", name)
}
