// AUTO-GENERATED by scripts/gen-vault-keys.mjs — DO NOT EDIT.
// Single source: proto/vault-keys.json. 새 key 추가 시 본 파일 X, JSON 만 수정.
//
// Phase 6 정공 (2026-05-13) — 옛 frontend 산재 string literal 통합.

export const VK_SYSTEM_TIMEZONE = "system:timezone";
export const VK_SYSTEM_WS_WATCHES = "system:ws-watches";
export const VK_SYSTEM_AI_MODEL = "system:llm:model";
export const VK_SYSTEM_AI_THINKING_LEVEL = "system:llm:thinking-level";
export const VK_SYSTEM_USER_PROMPT = "system:user-prompt";
export const VK_SYSTEM_AI_ASSISTANT_MODEL = "system:ai-router:model";
export const VK_SYSTEM_AI_ROUTER_ENABLED = "system:ai-router:enabled";
export const VK_LLM_ANTHROPIC_CACHE = "system:llm:anthropic-cache";
export const VK_SYSTEM_LAST_MODEL_BY_CATEGORY = "system:llm:last-by-category";
export const VK_ADMIN_ID = "FIREBAT_ADMIN_ID";
export const VK_ADMIN_PASSWORD = "FIREBAT_ADMIN_PASSWORD";
export const VK_COST_BUDGET = "system:cost:budget";
export const VK_IMAGE_MODEL = "system:image-model";
export const VK_IMAGE_SIZE = "system:image-size";
export const VK_IMAGE_QUALITY = "system:image-quality";
export const VK_SYSTEM_UI_LANG = "system:ui-lang";
export const VK_INTERNAL_MCP_TOKEN = "system:internal-mcp-token";
export const VK_INTERNAL_MCP_TOKEN_CREATED = "system:internal-mcp-token-created";

export const AUTH_SESSION_PREFIX = "auth:session:";
export const USER_SECRET_PREFIX = "user:";

/** 메인 LLM 모델 미설정 시 폴백 — settings.rs get_ai_model 기본값 single source. */
export const DEFAULT_LLM_MODEL_FALLBACK = "claude-sonnet-4-6";
/** 사고 수준 미설정 시 폴백 — settings.rs get_ai_thinking_level 기본값 single source. */
export const DEFAULT_THINKING_LEVEL = "medium";
/** 사용자 지시사항 최대 글자 수 — settings.rs + frontend SettingsModal 공통 single source. */
export const USER_PROMPT_MAX_CHARS = 2000;

/** 사용자 시크릿 key — `user:<name>` 형식. AI 가 모듈 호출 시 이 prefix 의 시크릿 자동 주입. */
export function vkUserSecret(name: string): string {
  return `user:${name}`;
}

/** Capability 설정 key — `system:capability:<id>:settings` 형식. CapabilityManager 가 사용. */
export function vkCapabilitySettings(capId: string): string {
  return `system:capability:${capId}:settings`;
}

/** Module 설정 key — `system:module:<name>:settings` 형식. ModuleManager / CapabilityManager 활성화 검사 시 사용. */
export function vkModuleSettings(name: string): string {
  return `system:module:${name}:settings`;
}
