// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Shared gRPC transport for all api-gen modules.

import { createGrpcTransport } from '@connectrpc/connect-node';

const baseUrl = process.env.FIREBAT_CORE_GRPC
  ? `http://${process.env.FIREBAT_CORE_GRPC}`
  : 'http://127.0.0.1:50051';

export const transport = createGrpcTransport({ baseUrl });
