// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / AiService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  AiCodeAssistRequest,
  AiCreatePendingRequest,
  AiProcessRequest,
  AiRequestActionWithToolsRequest,
  AiRunAgentJobRequest,
  AiService,
  AiSpawnSubAgentRequest,
  AiStorePlanRequest,
  BoolRequest,
  StringRequest,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const aiClient = createClient(AiService, transport);

export async function process(args: AiProcessRequest): Promise<RpcResult<string>> {
  try {
      const response = await aiClient.process(args ?? {});
      return { ok: true, data: response.text };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function requestActionWithTools(args: AiRequestActionWithToolsRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await aiClient.requestActionWithTools(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function codeAssist(args: AiCodeAssistRequest): Promise<RpcResult<string>> {
  try {
      const response = await aiClient.codeAssist(args ?? {});
      return { ok: true, data: response.text };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function runAgentJob(args: AiRunAgentJobRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await aiClient.runAgentJob(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function resolveCallTarget(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await aiClient.resolveCallTarget(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function spawnSubAgent(args: AiSpawnSubAgentRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await aiClient.spawnSubAgent(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function isSubAgentEnabled(): Promise<RpcResult<boolean>> {
  try {
      const response = await aiClient.isSubAgentEnabled({});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setSubAgentEnabled(args: BoolRequest): Promise<RpcResult<void>> {
  try {
      await aiClient.setSubAgentEnabled(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function createPending(args: AiCreatePendingRequest): Promise<RpcResult<string>> {
  try {
      const response = await aiClient.createPending(args ?? {});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getPending(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await aiClient.getPending(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function consumePending(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await aiClient.consumePending(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function rejectPending(args: StringRequest): Promise<RpcResult<boolean>> {
  try {
      const response = await aiClient.rejectPending(args ?? {});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function storePlan(args: AiStorePlanRequest): Promise<RpcResult<void>> {
  try {
      await aiClient.storePlan(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export const processAi = process;
