// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / AuthService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  AdminCredentialsPb,
  ApiTokenInfoPb,
  AuthLoginRequestSchema,
  AuthService,
  AuthSessionPb,
  AuthSetAdminCredentialsRequestSchema,
  AuthValidatePasswordPolicyRequestSchema,
  LoginResponsePb,
  StringRequestSchema,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const authClient = createClient(AuthService, transport);

export async function login(args: MessageInitShape<typeof AuthLoginRequestSchema>): Promise<RpcResult<LoginResponsePb>> {
  try {
      const response = await authClient.login(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function logout(args: MessageInitShape<typeof StringRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await authClient.logout(args ?? {});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function validateSession(args: MessageInitShape<typeof StringRequestSchema>): Promise<RpcResult<AuthSessionPb>> {
  try {
      const response = await authClient.validateSession(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function validateToken(args: MessageInitShape<typeof StringRequestSchema>): Promise<RpcResult<AuthSessionPb>> {
  try {
      const response = await authClient.validateToken(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function generateApiToken(args: MessageInitShape<typeof StringRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await authClient.generateApiToken(args ?? {});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function validateApiToken(args: MessageInitShape<typeof StringRequestSchema>): Promise<RpcResult<AuthSessionPb>> {
  try {
      const response = await authClient.validateApiToken(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function revokeApiTokens(): Promise<RpcResult<bigint>> {
  try {
      const response = await authClient.revokeApiTokens({});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getApiTokenInfo(): Promise<RpcResult<ApiTokenInfoPb>> {
  try {
      const response = await authClient.getApiTokenInfo({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getAdminCredentials(): Promise<RpcResult<AdminCredentialsPb>> {
  try {
      const response = await authClient.getAdminCredentials({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setAdminCredentials(args: MessageInitShape<typeof AuthSetAdminCredentialsRequestSchema>): Promise<RpcResult<void>> {
  try {
      await authClient.setAdminCredentials(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function isAdminSetup(): Promise<RpcResult<boolean>> {
  try {
      const response = await authClient.isAdminSetup({});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function verifyAdminPassword(args: MessageInitShape<typeof StringRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await authClient.verifyAdminPassword(args ?? {});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function validatePasswordPolicy(args: MessageInitShape<typeof AuthValidatePasswordPolicyRequestSchema>): Promise<RpcResult<void>> {
  try {
      await authClient.validatePasswordPolicy(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

