// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / CacheService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  CacheAggregateRequestSchema,
  CacheGrepRequestSchema,
  CacheReadRequestSchema,
  CacheService,
  StringRequestSchema,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const cacheClient = createClient(CacheService, transport);

export async function read(args: MessageInitShape<typeof CacheReadRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await cacheClient.read(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function grep(args: MessageInitShape<typeof CacheGrepRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await cacheClient.grep(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function aggregate(args: MessageInitShape<typeof CacheAggregateRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await cacheClient.aggregate(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function drop(args: MessageInitShape<typeof StringRequestSchema>): Promise<RpcResult<void>> {
  try {
      await cacheClient.drop(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export const cacheRead = read;
export const cacheGrep = grep;
export const cacheAggregate = aggregate;
export const cacheDrop = drop;
