// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / CapabilityService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  CapabilityProviderListPb,
  CapabilityProviderPb,
  CapabilityRegisterRequest,
  CapabilityService,
  CapabilitySetSettingsRequest,
  CapabilitySettingsPb,
  CapabilitySummaryListPb,
  StringRequest,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const capabilityClient = createClient(CapabilityService, transport);

export async function list(): Promise<RpcResult<unknown>> {
  try {
      const response = await capabilityClient.list({});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function register(args: CapabilityRegisterRequest): Promise<RpcResult<void>> {
  try {
      await capabilityClient.register(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getProviders(args: StringRequest): Promise<RpcResult<CapabilityProviderListPb>> {
  try {
      const response = await capabilityClient.getProviders(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listWithProviders(): Promise<RpcResult<CapabilitySummaryListPb>> {
  try {
      const response = await capabilityClient.listWithProviders({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function resolve(args: StringRequest): Promise<RpcResult<CapabilityProviderPb>> {
  try {
      const response = await capabilityClient.resolve(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getSettings(args: StringRequest): Promise<RpcResult<CapabilitySettingsPb>> {
  try {
      const response = await capabilityClient.getSettings(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setSettings(args: CapabilitySetSettingsRequest): Promise<RpcResult<void>> {
  try {
      await capabilityClient.setSettings(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export const listCapabilities = list;
export const getCapabilityProviders = getProviders;
export const listCapabilitiesWithProviders = listWithProviders;
export const resolveCapability = resolve;
export const registerCapability = register;
export const getCapabilitySettings = getSettings;
export const setCapabilitySettings = setSettings;
