// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / ChatbotService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  ChatbotAppendSystemMessageRequestSchema,
  ChatbotAppendUserMessageRequestSchema,
  ChatbotAuthenticateRequestSchema,
  ChatbotAuthenticateResponse,
  ChatbotConversationPb,
  ChatbotCreateInstanceRequestSchema,
  ChatbotDeleteConversationRequestSchema,
  ChatbotDeleteInstanceRequestSchema,
  ChatbotEnsureConversationRequestSchema,
  ChatbotGetConversationRequestSchema,
  ChatbotGetConversationResponse,
  ChatbotGetInstanceBySlugRequestSchema,
  ChatbotGetInstanceBySlugResponse,
  ChatbotGetInstanceRequestSchema,
  ChatbotGetInstanceResponse,
  ChatbotInstancePb,
  ChatbotListConversationsRequestSchema,
  ChatbotListMessagesRequestSchema,
  ChatbotMessagePb,
  ChatbotRotateApiTokenRequestSchema,
  ChatbotService,
  ChatbotUpdateConversationTitleRequestSchema,
  ChatbotUpdateInstanceRequestSchema,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';
import { unBigInt } from './_unbigint';

const chatbotClient = createClient(ChatbotService, transport);

export async function createInstance(args: MessageInitShape<typeof ChatbotCreateInstanceRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await chatbotClient.createInstance(args ?? {});
      return { ok: true, data: unBigInt(response.id) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listInstances(): Promise<RpcResult<ChatbotInstancePb[]>> {
  try {
      const response = await chatbotClient.listInstances({});
      return { ok: true, data: unBigInt(response.instances) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getInstance(args: MessageInitShape<typeof ChatbotGetInstanceRequestSchema>): Promise<RpcResult<ChatbotGetInstanceResponse>> {
  try {
      const response = await chatbotClient.getInstance(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getInstanceBySlug(args: MessageInitShape<typeof ChatbotGetInstanceBySlugRequestSchema>): Promise<RpcResult<ChatbotGetInstanceBySlugResponse>> {
  try {
      const response = await chatbotClient.getInstanceBySlug(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function updateInstance(args: MessageInitShape<typeof ChatbotUpdateInstanceRequestSchema>): Promise<RpcResult<void>> {
  try {
      await chatbotClient.updateInstance(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteInstance(args: MessageInitShape<typeof ChatbotDeleteInstanceRequestSchema>): Promise<RpcResult<void>> {
  try {
      await chatbotClient.deleteInstance(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function rotateApiToken(args: MessageInitShape<typeof ChatbotRotateApiTokenRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await chatbotClient.rotateApiToken(args ?? {});
      return { ok: true, data: unBigInt(response.newToken) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function authenticate(args: MessageInitShape<typeof ChatbotAuthenticateRequestSchema>): Promise<RpcResult<ChatbotAuthenticateResponse>> {
  try {
      const response = await chatbotClient.authenticate(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function ensureConversation(args: MessageInitShape<typeof ChatbotEnsureConversationRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await chatbotClient.ensureConversation(args ?? {});
      return { ok: true, data: unBigInt(response.conversationId) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listConversations(args: MessageInitShape<typeof ChatbotListConversationsRequestSchema>): Promise<RpcResult<ChatbotConversationPb[]>> {
  try {
      const response = await chatbotClient.listConversations(args ?? {});
      return { ok: true, data: unBigInt(response.conversations) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getConversation(args: MessageInitShape<typeof ChatbotGetConversationRequestSchema>): Promise<RpcResult<ChatbotGetConversationResponse>> {
  try {
      const response = await chatbotClient.getConversation(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteConversation(args: MessageInitShape<typeof ChatbotDeleteConversationRequestSchema>): Promise<RpcResult<void>> {
  try {
      await chatbotClient.deleteConversation(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function updateConversationTitle(args: MessageInitShape<typeof ChatbotUpdateConversationTitleRequestSchema>): Promise<RpcResult<void>> {
  try {
      await chatbotClient.updateConversationTitle(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function appendUserMessage(args: MessageInitShape<typeof ChatbotAppendUserMessageRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await chatbotClient.appendUserMessage(args ?? {});
      return { ok: true, data: unBigInt(response.messageId) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function appendSystemMessage(args: MessageInitShape<typeof ChatbotAppendSystemMessageRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await chatbotClient.appendSystemMessage(args ?? {});
      return { ok: true, data: unBigInt(response.messageId) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listMessages(args: MessageInitShape<typeof ChatbotListMessagesRequestSchema>): Promise<RpcResult<ChatbotMessagePb[]>> {
  try {
      const response = await chatbotClient.listMessages(args ?? {});
      return { ok: true, data: unBigInt(response.messages) };
  } catch (err) {
    return toRpcError(err);
  }
}
