// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / ConsolidationService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  ConsolidationAskLlmTextRequest,
  ConsolidationConsolidateInactiveRequest,
  ConsolidationConsolidateRequest,
  ConsolidationService,
  MemoryStatsPb,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const consolidationClient = createClient(ConsolidationService, transport);

export async function askLlmText(args: ConsolidationAskLlmTextRequest): Promise<RpcResult<string>> {
  try {
      const response = await consolidationClient.askLlmText(args ?? {});
      return { ok: true, data: response.text };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function consolidate(args: ConsolidationConsolidateRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await consolidationClient.consolidate(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function consolidateInactive(args: ConsolidationConsolidateInactiveRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await consolidationClient.consolidateInactive(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getMemoryStats(): Promise<RpcResult<MemoryStatsPb>> {
  try {
      const response = await consolidationClient.getMemoryStats({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

