// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / ConsolidationService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  ConsolidationAskLlmTextRequestSchema,
  ConsolidationConsolidateInactiveRequestSchema,
  ConsolidationConsolidateRequestSchema,
  ConsolidationGetMemoryStatsRequestSchema,
  ConsolidationService,
  MemoryStatsPb,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';
import { unBigInt } from './_unbigint';

const consolidationClient = createClient(ConsolidationService, transport);

export async function askLlmText(args: MessageInitShape<typeof ConsolidationAskLlmTextRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await consolidationClient.askLlmText(args ?? {});
      return { ok: true, data: unBigInt(response.text) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function consolidate(args: MessageInitShape<typeof ConsolidationConsolidateRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await consolidationClient.consolidate(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function consolidateInactive(args: MessageInitShape<typeof ConsolidationConsolidateInactiveRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await consolidationClient.consolidateInactive(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getMemoryStats(args: MessageInitShape<typeof ConsolidationGetMemoryStatsRequestSchema>): Promise<RpcResult<MemoryStatsPb>> {
  try {
      const response = await consolidationClient.getMemoryStats(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

