// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / ConversationService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  ConversationCreateShareRequest,
  ConversationGetCliSessionRequest,
  ConversationListPb,
  ConversationOwnerIdRequest,
  ConversationRecordPb,
  ConversationSaveRequest,
  ConversationSearchHistoryRequest,
  ConversationService,
  ConversationSetCliSessionRequest,
  HistorySearchResultPb,
  ShareResultPb,
  SharedConversationPb,
  StringRequest,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const conversationClient = createClient(ConversationService, transport);

export async function list(args: StringRequest): Promise<RpcResult<ConversationListPb>> {
  try {
      const response = await conversationClient.list(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function get(args: ConversationOwnerIdRequest): Promise<RpcResult<ConversationRecordPb>> {
  try {
      const response = await conversationClient.get(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function save(args: ConversationSaveRequest): Promise<RpcResult<void>> {
  try {
      await conversationClient.save(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteConversation(args: ConversationOwnerIdRequest): Promise<RpcResult<void>> {
  try {
      await conversationClient.delete(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function isDeleted(args: ConversationOwnerIdRequest): Promise<RpcResult<boolean>> {
  try {
      const response = await conversationClient.isDeleted(args ?? {});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listDeleted(args: StringRequest): Promise<RpcResult<ConversationListPb>> {
  try {
      const response = await conversationClient.listDeleted(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function restore(args: ConversationOwnerIdRequest): Promise<RpcResult<void>> {
  try {
      await conversationClient.restore(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function permanentDelete(args: ConversationOwnerIdRequest): Promise<RpcResult<void>> {
  try {
      await conversationClient.permanentDelete(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function searchHistory(args: ConversationSearchHistoryRequest): Promise<RpcResult<HistorySearchResultPb>> {
  try {
      const response = await conversationClient.searchHistory(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getCliSession(args: ConversationGetCliSessionRequest): Promise<RpcResult<string | null>> {
  try {
      const response = await conversationClient.getCliSession(args ?? {});
      return { ok: true, data: response.present ? response.value : null };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setCliSession(args: ConversationSetCliSessionRequest): Promise<RpcResult<void>> {
  try {
      await conversationClient.setCliSession(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function createShare(args: ConversationCreateShareRequest): Promise<RpcResult<ShareResultPb>> {
  try {
      const response = await conversationClient.createShare(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getShare(args: StringRequest): Promise<RpcResult<SharedConversationPb>> {
  try {
      const response = await conversationClient.getShare(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function cleanupExpiredShares(): Promise<RpcResult<bigint>> {
  try {
      const response = await conversationClient.cleanupExpiredShares({});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function cleanupOldDeleted(): Promise<RpcResult<bigint>> {
  try {
      const response = await conversationClient.cleanupOldDeleted({});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export const listConversations = list;
export const listDeletedConversations = listDeleted;
export const searchConversationHistory = searchHistory;
export const permanentDeleteConversation = permanentDelete;
export const cleanupOldDeletedConversations = cleanupOldDeleted;
export const isConversationDeleted = isDeleted;
export const getConversation = get;
export const saveConversation = save;
export const restoreConversation = restore;
