// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / ConversationService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  ConversationCreateShareRequestSchema,
  ConversationCreateShareResponse,
  ConversationDeleteRequestSchema,
  ConversationGetCliSessionRequestSchema,
  ConversationGetRequestSchema,
  ConversationGetResponse,
  ConversationGetShareRequestSchema,
  ConversationGetShareResponse,
  ConversationIsDeletedRequestSchema,
  ConversationListDeletedRequestSchema,
  ConversationListDeletedResponse,
  ConversationListRequestSchema,
  ConversationListResponse,
  ConversationPermanentDeleteRequestSchema,
  ConversationRestoreRequestSchema,
  ConversationSaveRequestSchema,
  ConversationSearchHistoryRequestSchema,
  ConversationSearchHistoryResponse,
  ConversationService,
  ConversationSetCliSessionRequestSchema,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const conversationClient = createClient(ConversationService, transport);

export async function list(args: MessageInitShape<typeof ConversationListRequestSchema>): Promise<RpcResult<ConversationListResponse>> {
  try {
      const response = await conversationClient.list(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function get(args: MessageInitShape<typeof ConversationGetRequestSchema>): Promise<RpcResult<ConversationGetResponse>> {
  try {
      const response = await conversationClient.get(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function save(args: MessageInitShape<typeof ConversationSaveRequestSchema>): Promise<RpcResult<void>> {
  try {
      await conversationClient.save(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteConversation(args: MessageInitShape<typeof ConversationDeleteRequestSchema>): Promise<RpcResult<void>> {
  try {
      await conversationClient.delete(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function isDeleted(args: MessageInitShape<typeof ConversationIsDeletedRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await conversationClient.isDeleted(args ?? {});
      return { ok: true, data: response.isDeleted };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listDeleted(args: MessageInitShape<typeof ConversationListDeletedRequestSchema>): Promise<RpcResult<ConversationListDeletedResponse>> {
  try {
      const response = await conversationClient.listDeleted(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function restore(args: MessageInitShape<typeof ConversationRestoreRequestSchema>): Promise<RpcResult<void>> {
  try {
      await conversationClient.restore(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function permanentDelete(args: MessageInitShape<typeof ConversationPermanentDeleteRequestSchema>): Promise<RpcResult<void>> {
  try {
      await conversationClient.permanentDelete(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function searchHistory(args: MessageInitShape<typeof ConversationSearchHistoryRequestSchema>): Promise<RpcResult<ConversationSearchHistoryResponse>> {
  try {
      const response = await conversationClient.searchHistory(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getCliSession(args: MessageInitShape<typeof ConversationGetCliSessionRequestSchema>): Promise<RpcResult<string | undefined>> {
  try {
      const response = await conversationClient.getCliSession(args ?? {});
      return { ok: true, data: response.sessionId };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setCliSession(args: MessageInitShape<typeof ConversationSetCliSessionRequestSchema>): Promise<RpcResult<void>> {
  try {
      await conversationClient.setCliSession(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function createShare(args: MessageInitShape<typeof ConversationCreateShareRequestSchema>): Promise<RpcResult<ConversationCreateShareResponse>> {
  try {
      const response = await conversationClient.createShare(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getShare(args: MessageInitShape<typeof ConversationGetShareRequestSchema>): Promise<RpcResult<ConversationGetShareResponse>> {
  try {
      const response = await conversationClient.getShare(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function cleanupExpiredShares(): Promise<RpcResult<bigint>> {
  try {
      const response = await conversationClient.cleanupExpiredShares({});
      return { ok: true, data: response.cleaned };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function cleanupOldDeleted(): Promise<RpcResult<bigint>> {
  try {
      const response = await conversationClient.cleanupOldDeleted({});
      return { ok: true, data: response.cleaned };
  } catch (err) {
    return toRpcError(err);
  }
}

export const listConversations = list;
export const listDeletedConversations = listDeleted;
export const searchConversationHistory = searchHistory;
export const permanentDeleteConversation = permanentDelete;
export const cleanupOldDeletedConversations = cleanupOldDeleted;
export const isConversationDeleted = isDeleted;
export const getConversation = get;
export const saveConversation = save;
export const restoreConversation = restore;
