// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / CostService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  BudgetCheckResultPb,
  CostBudgetPb,
  CostGetStatsRequest,
  CostService,
  CostSetBudgetRequest,
  LlmCostStatsSummaryPb,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const costClient = createClient(CostService, transport);

export async function getStats(args: CostGetStatsRequest): Promise<RpcResult<LlmCostStatsSummaryPb>> {
  try {
      const response = await costClient.getStats(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function flush(): Promise<RpcResult<void>> {
  try {
      await costClient.flush({});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getBudget(): Promise<RpcResult<CostBudgetPb>> {
  try {
      const response = await costClient.getBudget({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setBudget(args: CostSetBudgetRequest): Promise<RpcResult<void>> {
  try {
      await costClient.setBudget(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function checkBudget(): Promise<RpcResult<BudgetCheckResultPb>> {
  try {
      const response = await costClient.checkBudget({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export const getCostStats = getStats;
export const flushCost = flush;
export const getCostBudget = getBudget;
export const setCostBudget = setBudget;
export const checkCostBudget = checkBudget;
export const getLlmCostStats = getStats;
