// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / DatabaseService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  DatabaseQueryRequestSchema,
  DatabaseService,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const databaseClient = createClient(DatabaseService, transport);

export async function query(args: MessageInitShape<typeof DatabaseQueryRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await databaseClient.query(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export const queryDatabase = query;
