// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / EntityService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  EntityFactSaveRequestSchema,
  EntityFactUpdateRequestSchema,
  EntityRetrieveContextRequestSchema,
  EntitySaveRequestSchema,
  EntitySaveResultPb,
  EntitySearchFactsRequestSchema,
  EntitySearchRequestSchema,
  EntityService,
  EntityTimelineRequestSchema,
  EntityUpdateRequestSchema,
  FactSaveResultPb,
  NumberRequestSchema,
  StringRequestSchema,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const entityClient = createClient(EntityService, transport);

export async function save(args: MessageInitShape<typeof EntitySaveRequestSchema>): Promise<RpcResult<EntitySaveResultPb>> {
  try {
      const response = await entityClient.save(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function update(args: MessageInitShape<typeof EntityUpdateRequestSchema>): Promise<RpcResult<void>> {
  try {
      await entityClient.update(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteEntity(args: MessageInitShape<typeof NumberRequestSchema>): Promise<RpcResult<void>> {
  try {
      await entityClient.delete(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function get(args: MessageInitShape<typeof NumberRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.get(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function findByName(args: MessageInitShape<typeof StringRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.findByName(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function search(args: MessageInitShape<typeof EntitySearchRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.search(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function saveFact(args: MessageInitShape<typeof EntityFactSaveRequestSchema>): Promise<RpcResult<FactSaveResultPb>> {
  try {
      const response = await entityClient.saveFact(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function updateFact(args: MessageInitShape<typeof EntityFactUpdateRequestSchema>): Promise<RpcResult<void>> {
  try {
      await entityClient.updateFact(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteFact(args: MessageInitShape<typeof NumberRequestSchema>): Promise<RpcResult<void>> {
  try {
      await entityClient.deleteFact(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getFact(args: MessageInitShape<typeof NumberRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.getFact(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getTimeline(args: MessageInitShape<typeof EntityTimelineRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.getTimeline(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function searchFacts(args: MessageInitShape<typeof EntitySearchFactsRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.searchFacts(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function retrieveContext(args: MessageInitShape<typeof EntityRetrieveContextRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.retrieveContext(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function cleanupExpiredFacts(): Promise<RpcResult<bigint>> {
  try {
      const response = await entityClient.cleanupExpiredFacts({});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export const saveEntityFact = saveFact;
export const updateEntityFact = updateFact;
export const deleteEntityFact = deleteFact;
export const getEntityFact = getFact;
export const getEntityTimeline = getTimeline;
export const searchEntityFacts = searchFacts;
export const findEntityByName = findByName;
export const searchEntities = search;
export const saveEntity = save;
export const updateEntity = update;
export const getEntity = get;
