// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / EntityService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  EntityFactSaveRequest,
  EntityFactUpdateRequest,
  EntityRetrieveContextRequest,
  EntitySaveRequest,
  EntitySaveResultPb,
  EntitySearchFactsRequest,
  EntitySearchRequest,
  EntityService,
  EntityTimelineRequest,
  EntityUpdateRequest,
  FactSaveResultPb,
  NumberRequest,
  StringRequest,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const entityClient = createClient(EntityService, transport);

export async function save(args: EntitySaveRequest): Promise<RpcResult<EntitySaveResultPb>> {
  try {
      const response = await entityClient.save(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function update(args: EntityUpdateRequest): Promise<RpcResult<void>> {
  try {
      await entityClient.update(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteEntity(args: NumberRequest): Promise<RpcResult<void>> {
  try {
      await entityClient.delete(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function get(args: NumberRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.get(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function findByName(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.findByName(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function search(args: EntitySearchRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.search(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function saveFact(args: EntityFactSaveRequest): Promise<RpcResult<FactSaveResultPb>> {
  try {
      const response = await entityClient.saveFact(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function updateFact(args: EntityFactUpdateRequest): Promise<RpcResult<void>> {
  try {
      await entityClient.updateFact(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteFact(args: NumberRequest): Promise<RpcResult<void>> {
  try {
      await entityClient.deleteFact(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getFact(args: NumberRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.getFact(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getTimeline(args: EntityTimelineRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.getTimeline(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function searchFacts(args: EntitySearchFactsRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.searchFacts(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function retrieveContext(args: EntityRetrieveContextRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await entityClient.retrieveContext(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function cleanupExpiredFacts(): Promise<RpcResult<bigint>> {
  try {
      const response = await entityClient.cleanupExpiredFacts({});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export const saveEntityFact = saveFact;
export const updateEntityFact = updateFact;
export const deleteEntityFact = deleteFact;
export const getEntityFact = getFact;
export const getEntityTimeline = getTimeline;
export const searchEntityFacts = searchFacts;
export const findEntityByName = findByName;
export const searchEntities = search;
export const saveEntity = save;
export const updateEntity = update;
export const getEntity = get;
