// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / EpisodicService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  EpisodicLinkEntityRequest,
  EpisodicListByEntityRequest,
  EpisodicListRecentRequest,
  EpisodicSaveEventRequest,
  EpisodicSearchEventsRequest,
  EpisodicService,
  EpisodicUpdateEventRequest,
  FactSaveResultPb,
  NumberRequest,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const episodicClient = createClient(EpisodicService, transport);

export async function saveEvent(args: EpisodicSaveEventRequest): Promise<RpcResult<FactSaveResultPb>> {
  try {
      const response = await episodicClient.saveEvent(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function updateEvent(args: EpisodicUpdateEventRequest): Promise<RpcResult<void>> {
  try {
      await episodicClient.updateEvent(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteEvent(args: NumberRequest): Promise<RpcResult<void>> {
  try {
      await episodicClient.deleteEvent(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getEvent(args: NumberRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await episodicClient.getEvent(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function searchEvents(args: EpisodicSearchEventsRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await episodicClient.searchEvents(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listRecent(args: EpisodicListRecentRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await episodicClient.listRecent(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listByEntity(args: EpisodicListByEntityRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await episodicClient.listByEntity(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function linkEntity(args: EpisodicLinkEntityRequest): Promise<RpcResult<void>> {
  try {
      await episodicClient.linkEntity(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function unlinkEntity(args: EpisodicLinkEntityRequest): Promise<RpcResult<void>> {
  try {
      await episodicClient.unlinkEntity(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function cleanupExpired(): Promise<RpcResult<bigint>> {
  try {
      const response = await episodicClient.cleanupExpired({});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export const listRecentEvents = listRecent;
export const listEventsByEntity = listByEntity;
export const linkEventEntity = linkEntity;
export const unlinkEventEntity = unlinkEntity;
export const cleanupExpiredEvents = cleanupExpired;
