// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / EpisodicService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  EpisodicDeleteEventRequestSchema,
  EpisodicGetEventRequestSchema,
  EpisodicLinkEntityRequestSchema,
  EpisodicListByEntityRequestSchema,
  EpisodicListRecentRequestSchema,
  EpisodicSaveEventRequestSchema,
  EpisodicSaveEventResponse,
  EpisodicSearchEventsRequestSchema,
  EpisodicService,
  EpisodicUnlinkEntityRequestSchema,
  EpisodicUpdateEventRequestSchema,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';
import { unBigInt } from './_unbigint';

const episodicClient = createClient(EpisodicService, transport);

export async function saveEvent(args: MessageInitShape<typeof EpisodicSaveEventRequestSchema>): Promise<RpcResult<EpisodicSaveEventResponse>> {
  try {
      const response = await episodicClient.saveEvent(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function updateEvent(args: MessageInitShape<typeof EpisodicUpdateEventRequestSchema>): Promise<RpcResult<void>> {
  try {
      await episodicClient.updateEvent(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteEvent(args: MessageInitShape<typeof EpisodicDeleteEventRequestSchema>): Promise<RpcResult<void>> {
  try {
      await episodicClient.deleteEvent(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getEvent(args: MessageInitShape<typeof EpisodicGetEventRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await episodicClient.getEvent(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function searchEvents(args: MessageInitShape<typeof EpisodicSearchEventsRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await episodicClient.searchEvents(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listRecent(args: MessageInitShape<typeof EpisodicListRecentRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await episodicClient.listRecent(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listByEntity(args: MessageInitShape<typeof EpisodicListByEntityRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await episodicClient.listByEntity(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function linkEntity(args: MessageInitShape<typeof EpisodicLinkEntityRequestSchema>): Promise<RpcResult<void>> {
  try {
      await episodicClient.linkEntity(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function unlinkEntity(args: MessageInitShape<typeof EpisodicUnlinkEntityRequestSchema>): Promise<RpcResult<void>> {
  try {
      await episodicClient.unlinkEntity(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function cleanupExpired(): Promise<RpcResult<bigint>> {
  try {
      const response = await episodicClient.cleanupExpired({});
      return { ok: true, data: unBigInt(response.cleaned) };
  } catch (err) {
    return toRpcError(err);
  }
}

export const listRecentEvents = listRecent;
export const listEventsByEntity = listByEntity;
export const linkEventEntity = linkEntity;
export const unlinkEventEntity = unlinkEntity;
export const cleanupExpiredEvents = cleanupExpired;
