// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / HubService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  HubAppendSystemMessageRequestSchema,
  HubAppendUserMessageRequestSchema,
  HubAuthenticateRequestSchema,
  HubAuthenticateResponse,
  HubConversationPb,
  HubCreateInstanceRequestSchema,
  HubDeleteConversationRequestSchema,
  HubDeleteInstanceRequestSchema,
  HubEnsureConversationRequestSchema,
  HubGetConversationRequestSchema,
  HubGetConversationResponse,
  HubGetInstanceBySlugRequestSchema,
  HubGetInstanceBySlugResponse,
  HubGetInstanceRequestSchema,
  HubGetInstanceResponse,
  HubInstancePb,
  HubListConversationsRequestSchema,
  HubListMessagesRequestSchema,
  HubMessagePb,
  HubRotateApiTokenRequestSchema,
  HubSendMessageRequestSchema,
  HubSendMessageResponse,
  HubService,
  HubUpdateConversationTitleRequestSchema,
  HubUpdateInstanceRequestSchema,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';
import { unBigInt } from './_unbigint';

const hubClient = createClient(HubService, transport);

export async function createInstance(args: MessageInitShape<typeof HubCreateInstanceRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await hubClient.createInstance(args ?? {});
      return { ok: true, data: unBigInt(response.id) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listInstances(): Promise<RpcResult<HubInstancePb[]>> {
  try {
      const response = await hubClient.listInstances({});
      return { ok: true, data: unBigInt(response.instances) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getInstance(args: MessageInitShape<typeof HubGetInstanceRequestSchema>): Promise<RpcResult<HubGetInstanceResponse>> {
  try {
      const response = await hubClient.getInstance(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getInstanceBySlug(args: MessageInitShape<typeof HubGetInstanceBySlugRequestSchema>): Promise<RpcResult<HubGetInstanceBySlugResponse>> {
  try {
      const response = await hubClient.getInstanceBySlug(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function updateInstance(args: MessageInitShape<typeof HubUpdateInstanceRequestSchema>): Promise<RpcResult<void>> {
  try {
      await hubClient.updateInstance(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteInstance(args: MessageInitShape<typeof HubDeleteInstanceRequestSchema>): Promise<RpcResult<void>> {
  try {
      await hubClient.deleteInstance(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function rotateApiToken(args: MessageInitShape<typeof HubRotateApiTokenRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await hubClient.rotateApiToken(args ?? {});
      return { ok: true, data: unBigInt(response.newToken) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function authenticate(args: MessageInitShape<typeof HubAuthenticateRequestSchema>): Promise<RpcResult<HubAuthenticateResponse>> {
  try {
      const response = await hubClient.authenticate(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function ensureConversation(args: MessageInitShape<typeof HubEnsureConversationRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await hubClient.ensureConversation(args ?? {});
      return { ok: true, data: unBigInt(response.conversationId) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listConversations(args: MessageInitShape<typeof HubListConversationsRequestSchema>): Promise<RpcResult<HubConversationPb[]>> {
  try {
      const response = await hubClient.listConversations(args ?? {});
      return { ok: true, data: unBigInt(response.conversations) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getConversation(args: MessageInitShape<typeof HubGetConversationRequestSchema>): Promise<RpcResult<HubGetConversationResponse>> {
  try {
      const response = await hubClient.getConversation(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteConversation(args: MessageInitShape<typeof HubDeleteConversationRequestSchema>): Promise<RpcResult<void>> {
  try {
      await hubClient.deleteConversation(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function updateConversationTitle(args: MessageInitShape<typeof HubUpdateConversationTitleRequestSchema>): Promise<RpcResult<void>> {
  try {
      await hubClient.updateConversationTitle(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function appendUserMessage(args: MessageInitShape<typeof HubAppendUserMessageRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await hubClient.appendUserMessage(args ?? {});
      return { ok: true, data: unBigInt(response.messageId) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function appendSystemMessage(args: MessageInitShape<typeof HubAppendSystemMessageRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await hubClient.appendSystemMessage(args ?? {});
      return { ok: true, data: unBigInt(response.messageId) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listMessages(args: MessageInitShape<typeof HubListMessagesRequestSchema>): Promise<RpcResult<HubMessagePb[]>> {
  try {
      const response = await hubClient.listMessages(args ?? {});
      return { ok: true, data: unBigInt(response.messages) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function sendMessage(args: MessageInitShape<typeof HubSendMessageRequestSchema>): Promise<RpcResult<HubSendMessageResponse>> {
  try {
      const response = await hubClient.sendMessage(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}
