// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// 타입 재export — RpcResult / RpcErrorCode / toRpcError.
// service-specific import 권장: `import { savePage } from '@/lib/api-gen/page'`
// (collision 회피 + tree-shaking 친화)

export * from './types';
