// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / LibraryService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  LibraryCreateReferenceRequestSchema,
  LibraryDeleteReferenceRequestSchema,
  LibraryDeleteSourceRequestSchema,
  LibraryGetSourceRequestSchema,
  LibraryGetSourceResponse,
  LibraryHitPb,
  LibraryListReferencesRequestSchema,
  LibraryListSourcesRequestSchema,
  LibraryReextractSourceRequestSchema,
  LibraryReferencePb,
  LibrarySearchRequestSchema,
  LibraryService,
  LibrarySourcePb,
  LibraryUploadSourceRequestSchema,
  LibraryUploadSourceResponse,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';
import { unBigInt } from './_unbigint';

const libraryClient = createClient(LibraryService, transport);

export async function createReference(args: MessageInitShape<typeof LibraryCreateReferenceRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await libraryClient.createReference(args ?? {});
      return { ok: true, data: unBigInt(response.id) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listReferences(args: MessageInitShape<typeof LibraryListReferencesRequestSchema>): Promise<RpcResult<LibraryReferencePb[]>> {
  try {
      const response = await libraryClient.listReferences(args ?? {});
      return { ok: true, data: unBigInt(response.references) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteReference(args: MessageInitShape<typeof LibraryDeleteReferenceRequestSchema>): Promise<RpcResult<void>> {
  try {
      await libraryClient.deleteReference(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function uploadSource(args: MessageInitShape<typeof LibraryUploadSourceRequestSchema>): Promise<RpcResult<LibraryUploadSourceResponse>> {
  try {
      const response = await libraryClient.uploadSource(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listSources(args: MessageInitShape<typeof LibraryListSourcesRequestSchema>): Promise<RpcResult<LibrarySourcePb[]>> {
  try {
      const response = await libraryClient.listSources(args ?? {});
      return { ok: true, data: unBigInt(response.sources) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getSource(args: MessageInitShape<typeof LibraryGetSourceRequestSchema>): Promise<RpcResult<LibraryGetSourceResponse>> {
  try {
      const response = await libraryClient.getSource(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteSource(args: MessageInitShape<typeof LibraryDeleteSourceRequestSchema>): Promise<RpcResult<void>> {
  try {
      await libraryClient.deleteSource(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function reextractSource(args: MessageInitShape<typeof LibraryReextractSourceRequestSchema>): Promise<RpcResult<bigint>> {
  try {
      const response = await libraryClient.reextractSource(args ?? {});
      return { ok: true, data: unBigInt(response.chunkCount) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function search(args: MessageInitShape<typeof LibrarySearchRequestSchema>): Promise<RpcResult<LibraryHitPb[]>> {
  try {
      const response = await libraryClient.search(args ?? {});
      return { ok: true, data: unBigInt(response.hits) };
  } catch (err) {
    return toRpcError(err);
  }
}
