// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / LifecycleService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  HealthInfo,
  LifecycleCaptureExceptionRequestSchema,
  LifecycleService,
  NumberRequestSchema,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const lifecycleClient = createClient(LifecycleService, transport);

export async function health(): Promise<RpcResult<HealthInfo>> {
  try {
      const response = await lifecycleClient.health({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function captureException(args: MessageInitShape<typeof LifecycleCaptureExceptionRequestSchema>): Promise<RpcResult<void>> {
  try {
      await lifecycleClient.captureException(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function gracefulShutdown(args: MessageInitShape<typeof NumberRequestSchema>): Promise<RpcResult<void>> {
  try {
      await lifecycleClient.gracefulShutdown(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

