// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / LogService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  LogEntryPb,
  LogQueryRequestSchema,
  LogService,
  SetLogFilterRequestSchema,
  SetLogFilterResponse,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';
import { unBigInt } from './_unbigint';

const logClient = createClient(LogService, transport);

export async function queryLogs(args: MessageInitShape<typeof LogQueryRequestSchema>): Promise<RpcResult<LogEntryPb[]>> {
  try {
      const response = await logClient.queryLogs(args ?? {});
      return { ok: true, data: unBigInt(response.entries) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setLogFilter(args: MessageInitShape<typeof SetLogFilterRequestSchema>): Promise<RpcResult<SetLogFilterResponse>> {
  try {
      const response = await logClient.setLogFilter(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}
