// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / McpService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  McpAddServerRequestSchema,
  McpCallToolRequestSchema,
  McpListToolsRequestSchema,
  McpRemoveServerRequestSchema,
  McpService,
  McpToolInfoPb,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';
import { unBigInt } from './_unbigint';

const mcpClient = createClient(McpService, transport);

export async function listServers(): Promise<RpcResult<unknown>> {
  try {
      const response = await mcpClient.listServers({});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function addServer(args: MessageInitShape<typeof McpAddServerRequestSchema>): Promise<RpcResult<void>> {
  try {
      await mcpClient.addServer(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function removeServer(args: MessageInitShape<typeof McpRemoveServerRequestSchema>): Promise<RpcResult<void>> {
  try {
      await mcpClient.removeServer(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listTools(args: MessageInitShape<typeof McpListToolsRequestSchema>): Promise<RpcResult<McpToolInfoPb[]>> {
  try {
      const response = await mcpClient.listTools(args ?? {});
      return { ok: true, data: unBigInt(response.tools) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listAllTools(): Promise<RpcResult<McpToolInfoPb[]>> {
  try {
      const response = await mcpClient.listAllTools({});
      return { ok: true, data: unBigInt(response.tools) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function callTool(args: MessageInitShape<typeof McpCallToolRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await mcpClient.callTool(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export const listMcpServers = listServers;
export const saveMcpServer = addServer;
export const addMcpServer = addServer;
export const removeMcpServer = removeServer;
export const listMcpTools = listTools;
export const listAllMcpTools = listAllTools;
export const callMcpTool = callTool;
