// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / MediaService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  ImageModelPb,
  MediaGenerateRequestSchema,
  MediaGenerateResponse,
  MediaIsReadyRequestSchema,
  MediaListRequestSchema,
  MediaListResultPb,
  MediaReadPb,
  MediaReadRequestSchema,
  MediaReadTempAttachmentRequestSchema,
  MediaReadTempAttachmentResponse,
  MediaRegenerateRequestSchema,
  MediaRegenerateResponse,
  MediaRemoveRequestSchema,
  MediaSaveRequestSchema,
  MediaSaveResultPb,
  MediaSaveTempAttachmentRequestSchema,
  MediaService,
  MediaSetImageDefaultQualityRequestSchema,
  MediaSetImageDefaultSizeRequestSchema,
  MediaSetImageModelRequestSchema,
  MediaStartGenerationRequestSchema,
  StartGenerationPb,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';
import { unBigInt } from './_unbigint';

const mediaClient = createClient(MediaService, transport);

export async function read(args: MessageInitShape<typeof MediaReadRequestSchema>): Promise<RpcResult<MediaReadPb>> {
  try {
      const response = await mediaClient.read(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function list(args: MessageInitShape<typeof MediaListRequestSchema>): Promise<RpcResult<MediaListResultPb>> {
  try {
      const response = await mediaClient.list(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function remove(args: MessageInitShape<typeof MediaRemoveRequestSchema>): Promise<RpcResult<void>> {
  try {
      await mediaClient.remove(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function isReady(args: MessageInitShape<typeof MediaIsReadyRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await mediaClient.isReady(args ?? {});
      return { ok: true, data: unBigInt(response.ready) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function startGeneration(args: MessageInitShape<typeof MediaStartGenerationRequestSchema>): Promise<RpcResult<StartGenerationPb>> {
  try {
      const response = await mediaClient.startGeneration(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function generate(args: MessageInitShape<typeof MediaGenerateRequestSchema>): Promise<RpcResult<MediaGenerateResponse>> {
  try {
      const response = await mediaClient.generate(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function regenerate(args: MessageInitShape<typeof MediaRegenerateRequestSchema>): Promise<RpcResult<MediaRegenerateResponse>> {
  try {
      const response = await mediaClient.regenerate(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function save(args: MessageInitShape<typeof MediaSaveRequestSchema>): Promise<RpcResult<MediaSaveResultPb>> {
  try {
      const response = await mediaClient.save(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getImageModel(): Promise<RpcResult<string>> {
  try {
      const response = await mediaClient.getImageModel({});
      return { ok: true, data: unBigInt(response.model) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setImageModel(args: MessageInitShape<typeof MediaSetImageModelRequestSchema>): Promise<RpcResult<void>> {
  try {
      await mediaClient.setImageModel(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getAvailableImageModels(): Promise<RpcResult<ImageModelPb[]>> {
  try {
      const response = await mediaClient.getAvailableImageModels({});
      return { ok: true, data: unBigInt(response.models) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getImageDefaultSize(): Promise<RpcResult<string | null>> {
  try {
      const response = await mediaClient.getImageDefaultSize({});
      return { ok: true, data: response.present ? unBigInt(response.size) : null };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setImageDefaultSize(args: MessageInitShape<typeof MediaSetImageDefaultSizeRequestSchema>): Promise<RpcResult<void>> {
  try {
      await mediaClient.setImageDefaultSize(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getImageDefaultQuality(): Promise<RpcResult<string | null>> {
  try {
      const response = await mediaClient.getImageDefaultQuality({});
      return { ok: true, data: response.present ? unBigInt(response.quality) : null };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setImageDefaultQuality(args: MessageInitShape<typeof MediaSetImageDefaultQualityRequestSchema>): Promise<RpcResult<void>> {
  try {
      await mediaClient.setImageDefaultQuality(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getImageSettings(): Promise<RpcResult<unknown>> {
  try {
      const response = await mediaClient.getImageSettings({});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function saveTempAttachment(args: MessageInitShape<typeof MediaSaveTempAttachmentRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await mediaClient.saveTempAttachment(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function cleanupOldAttachments(): Promise<RpcResult<bigint>> {
  try {
      const response = await mediaClient.cleanupOldAttachments({});
      return { ok: true, data: unBigInt(response.deletedCount) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function readTempAttachment(args: MessageInitShape<typeof MediaReadTempAttachmentRequestSchema>): Promise<RpcResult<MediaReadTempAttachmentResponse>> {
  try {
      const response = await mediaClient.readTempAttachment(args ?? {});
      return { ok: true, data: unBigInt(response) };
  } catch (err) {
    return toRpcError(err);
  }
}

export const listMedia = list;
export const listImageModels = getAvailableImageModels;
export const isMediaReady = isReady;
export const saveUpload = save;
export const regenerateImage = regenerate;
export const startImageGeneration = startGeneration;
export const removeMedia = remove;
export const readMedia = read;
export const generateImage = generate;
