// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / MemoryService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  MemoryDeleteFileRequestSchema,
  MemoryReadFileRequestSchema,
  MemorySaveFileRequestSchema,
  MemoryService,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const memoryClient = createClient(MemoryService, transport);

export async function getIndex(): Promise<RpcResult<string>> {
  try {
      const response = await memoryClient.getIndex({});
      return { ok: true, data: response.content };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function readFile(args: MessageInitShape<typeof MemoryReadFileRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await memoryClient.readFile(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listFiles(): Promise<RpcResult<unknown>> {
  try {
      const response = await memoryClient.listFiles({});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function saveFile(args: MessageInitShape<typeof MemorySaveFileRequestSchema>): Promise<RpcResult<void>> {
  try {
      await memoryClient.saveFile(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteFile(args: MessageInitShape<typeof MemoryDeleteFileRequestSchema>): Promise<RpcResult<void>> {
  try {
      await memoryClient.deleteFile(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export const getMemoryIndex = getIndex;
export const readMemoryFile = readFile;
export const listMemoryFiles = listFiles;
export const saveMemoryFile = saveFile;
export const deleteMemoryFile = deleteFile;
