// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / ModuleService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  ModuleEntryPb,
  ModuleGetConfigRequestSchema,
  ModuleGetLangRequestSchema,
  ModuleGetPackageStatusRequestSchema,
  ModuleGetSchemaRequestSchema,
  ModuleGetSettingsRequestSchema,
  ModuleInstallPackagesRequestSchema,
  ModuleIsEnabledRequestSchema,
  ModuleOutputPb,
  ModuleRunRequestSchema,
  ModuleService,
  ModuleSetEnabledRequestSchema,
  ModuleSetSettingsRequestSchema,
  PackageStatusPb,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const moduleClient = createClient(ModuleService, transport);

export async function run(args: MessageInitShape<typeof ModuleRunRequestSchema>): Promise<RpcResult<ModuleOutputPb>> {
  try {
      const response = await moduleClient.run(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listSystem(): Promise<RpcResult<ModuleEntryPb[]>> {
  try {
      const response = await moduleClient.listSystem({});
      return { ok: true, data: response.entries };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listUser(): Promise<RpcResult<ModuleEntryPb[]>> {
  try {
      const response = await moduleClient.listUser({});
      return { ok: true, data: response.entries };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getSchema(args: MessageInitShape<typeof ModuleGetSchemaRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await moduleClient.getSchema(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getSettings(args: MessageInitShape<typeof ModuleGetSettingsRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await moduleClient.getSettings(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getConfig(args: MessageInitShape<typeof ModuleGetConfigRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await moduleClient.getConfig(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setSettings(args: MessageInitShape<typeof ModuleSetSettingsRequestSchema>): Promise<RpcResult<void>> {
  try {
      await moduleClient.setSettings(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function isEnabled(args: MessageInitShape<typeof ModuleIsEnabledRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await moduleClient.isEnabled(args ?? {});
      return { ok: true, data: response.enabled };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setEnabled(args: MessageInitShape<typeof ModuleSetEnabledRequestSchema>): Promise<RpcResult<void>> {
  try {
      await moduleClient.setEnabled(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getCmsSettings(): Promise<RpcResult<unknown>> {
  try {
      const response = await moduleClient.getCmsSettings({});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getLang(args: MessageInitShape<typeof ModuleGetLangRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await moduleClient.getLang(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getKakaoMapJsKey(): Promise<RpcResult<string>> {
  try {
      const response = await moduleClient.getKakaoMapJsKey({});
      return { ok: true, data: response.key };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function installPackages(args: MessageInitShape<typeof ModuleInstallPackagesRequestSchema>): Promise<RpcResult<string[]>> {
  try {
      const response = await moduleClient.installPackages(args ?? {});
      return { ok: true, data: response.jobIds };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getPackageStatus(args: MessageInitShape<typeof ModuleGetPackageStatusRequestSchema>): Promise<RpcResult<PackageStatusPb[]>> {
  try {
      const response = await moduleClient.getPackageStatus(args ?? {});
      return { ok: true, data: response.packages };
  } catch (err) {
    return toRpcError(err);
  }
}

export const listSystemModules = listSystem;
export const listUserModules = listUser;
export const getSystemModules = listSystem;
export const getUserModules = listUser;
export const isModuleEnabled = isEnabled;
export const getModuleSchema = getSchema;
export const getModuleConfig = getConfig;
export const runModule = run;
export const sandboxExecute = run;
export const setModuleEnabled = setEnabled;
export const setModuleSettings = setSettings;
export const getModuleSettings = getSettings;
export const getModuleLang = getLang;
