// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / NetworkService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  NetworkFetchRequest,
  NetworkService,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const networkClient = createClient(NetworkService, transport);

export async function fetch(args: NetworkFetchRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await networkClient.fetch(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export const networkFetch = fetch;
