// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / PageService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  MediaUsageListPb,
  PageDeleteRequestSchema,
  PageFindMediaUsageRequestSchema,
  PageFindRelatedRequestSchema,
  PageFindRelatedResponse,
  PageGetRedirectRequestSchema,
  PageGetRequestSchema,
  PageListResponse,
  PageRecordPb,
  PageRenameRequestSchema,
  PageSaveRequestSchema,
  PageSaveResultPb,
  PageSearchRequestSchema,
  PageSearchResponse,
  PageService,
  PageSetVisibilityRequestSchema,
  PageVerifyPasswordRequestSchema,
  TagListPb,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const pageClient = createClient(PageService, transport);

export async function list(): Promise<RpcResult<PageListResponse>> {
  try {
      const response = await pageClient.list({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function search(args: MessageInitShape<typeof PageSearchRequestSchema>): Promise<RpcResult<PageSearchResponse>> {
  try {
      const response = await pageClient.search(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function get(args: MessageInitShape<typeof PageGetRequestSchema>): Promise<RpcResult<PageRecordPb>> {
  try {
      const response = await pageClient.get(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function save(args: MessageInitShape<typeof PageSaveRequestSchema>): Promise<RpcResult<PageSaveResultPb>> {
  try {
      const response = await pageClient.save(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deletePage(args: MessageInitShape<typeof PageDeleteRequestSchema>): Promise<RpcResult<void>> {
  try {
      await pageClient.delete(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function rename(args: MessageInitShape<typeof PageRenameRequestSchema>): Promise<RpcResult<void>> {
  try {
      await pageClient.rename(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getRedirect(args: MessageInitShape<typeof PageGetRedirectRequestSchema>): Promise<RpcResult<string | null>> {
  try {
      const response = await pageClient.getRedirect(args ?? {});
      return { ok: true, data: response.present ? response.value : null };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listStatic(): Promise<RpcResult<string[]>> {
  try {
      const response = await pageClient.listStatic({});
      return { ok: true, data: response.slugs };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function findMediaUsage(args: MessageInitShape<typeof PageFindMediaUsageRequestSchema>): Promise<RpcResult<MediaUsageListPb>> {
  try {
      const response = await pageClient.findMediaUsage(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setVisibility(args: MessageInitShape<typeof PageSetVisibilityRequestSchema>): Promise<RpcResult<void>> {
  try {
      await pageClient.setVisibility(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function verifyPassword(args: MessageInitShape<typeof PageVerifyPasswordRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await pageClient.verifyPassword(args ?? {});
      return { ok: true, data: response.valid };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function findRelated(args: MessageInitShape<typeof PageFindRelatedRequestSchema>): Promise<RpcResult<PageFindRelatedResponse>> {
  try {
      const response = await pageClient.findRelated(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listAllTags(): Promise<RpcResult<TagListPb>> {
  try {
      const response = await pageClient.listAllTags({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export const listPages = list;
export const searchPages = search;
export const listStaticPages = listStatic;
export const findRelatedPages = findRelated;
export const getPageRedirect = getRedirect;
export const verifyPagePassword = verifyPassword;
export const savePage = save;
export const renamePage = rename;
export const getPage = get;
export const setPageVisibility = setVisibility;
