// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / ProjectService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  ProjectListPb,
  ProjectRenameRequest,
  ProjectService,
  ProjectSetConfigRequest,
  ProjectSetVisibilityRequest,
  ProjectVerifyPasswordRequest,
  StringRequest,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const projectClient = createClient(ProjectService, transport);

export async function scan(): Promise<RpcResult<ProjectListPb>> {
  try {
      const response = await projectClient.scan({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setVisibility(args: ProjectSetVisibilityRequest): Promise<RpcResult<void>> {
  try {
      await projectClient.setVisibility(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getVisibility(args: StringRequest): Promise<RpcResult<string>> {
  try {
      const response = await projectClient.getVisibility(args ?? {});
      return { ok: true, data: response.visibility };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getConfig(args: StringRequest): Promise<RpcResult<string>> {
  try {
      const response = await projectClient.getConfig(args ?? {});
      return { ok: true, data: response.rawJson };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setConfig(args: ProjectSetConfigRequest): Promise<RpcResult<void>> {
  try {
      await projectClient.setConfig(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function verifyPassword(args: ProjectVerifyPasswordRequest): Promise<RpcResult<boolean>> {
  try {
      const response = await projectClient.verifyPassword(args ?? {});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteProject(args: StringRequest): Promise<RpcResult<void>> {
  try {
      await projectClient.delete(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function rename(args: ProjectRenameRequest): Promise<RpcResult<void>> {
  try {
      await projectClient.rename(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export const scanProjects = scan;
export const listProjects = scan;
export const verifyProjectPassword = verifyPassword;
export const getProjectConfig = getConfig;
