// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / ProjectService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  ProjectDeleteRequestSchema,
  ProjectGetConfigRequestSchema,
  ProjectGetVisibilityRequestSchema,
  ProjectListPb,
  ProjectRenameRequestSchema,
  ProjectService,
  ProjectSetConfigRequestSchema,
  ProjectSetVisibilityRequestSchema,
  ProjectVerifyPasswordRequestSchema,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const projectClient = createClient(ProjectService, transport);

export async function scan(): Promise<RpcResult<ProjectListPb>> {
  try {
      const response = await projectClient.scan({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setVisibility(args: MessageInitShape<typeof ProjectSetVisibilityRequestSchema>): Promise<RpcResult<void>> {
  try {
      await projectClient.setVisibility(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getVisibility(args: MessageInitShape<typeof ProjectGetVisibilityRequestSchema>): Promise<RpcResult<string>> {
  try {
      const response = await projectClient.getVisibility(args ?? {});
      return { ok: true, data: response.visibility };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getConfig(args: MessageInitShape<typeof ProjectGetConfigRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await projectClient.getConfig(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setConfig(args: MessageInitShape<typeof ProjectSetConfigRequestSchema>): Promise<RpcResult<void>> {
  try {
      await projectClient.setConfig(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function verifyPassword(args: MessageInitShape<typeof ProjectVerifyPasswordRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await projectClient.verifyPassword(args ?? {});
      return { ok: true, data: response.valid };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteProject(args: MessageInitShape<typeof ProjectDeleteRequestSchema>): Promise<RpcResult<void>> {
  try {
      await projectClient.delete(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function rename(args: MessageInitShape<typeof ProjectRenameRequestSchema>): Promise<RpcResult<void>> {
  try {
      await projectClient.rename(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export const scanProjects = scan;
export const listProjects = scan;
export const verifyProjectPassword = verifyPassword;
export const getProjectConfig = getConfig;
export const setProjectVisibility = setVisibility;
export const setProjectConfig = setConfig;
