// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / ScheduleService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  CancelCronRequestSchema,
  CronJobListPb,
  CronLogListPb,
  CronNotificationListPb,
  GetCronLogsRequestSchema,
  RunCronNowRequestSchema,
  ScheduleCronRequestSchema,
  ScheduleService,
  UpdateCronRequestSchema,
  ValidatePipelineRequestSchema,
  ValidatePipelineResultPb,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const scheduleClient = createClient(ScheduleService, transport);

export async function scheduleCron(args: MessageInitShape<typeof ScheduleCronRequestSchema>): Promise<RpcResult<void>> {
  try {
      await scheduleClient.scheduleCron(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function cancelCron(args: MessageInitShape<typeof CancelCronRequestSchema>): Promise<RpcResult<void>> {
  try {
      await scheduleClient.cancelCron(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function updateCron(args: MessageInitShape<typeof UpdateCronRequestSchema>): Promise<RpcResult<void>> {
  try {
      await scheduleClient.updateCron(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listCron(): Promise<RpcResult<CronJobListPb>> {
  try {
      const response = await scheduleClient.listCron({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getLogs(args: MessageInitShape<typeof GetCronLogsRequestSchema>): Promise<RpcResult<CronLogListPb>> {
  try {
      const response = await scheduleClient.getLogs(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function clearLogs(): Promise<RpcResult<void>> {
  try {
      await scheduleClient.clearLogs({});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function consumeNotifications(): Promise<RpcResult<CronNotificationListPb>> {
  try {
      const response = await scheduleClient.consumeNotifications({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function runNow(args: MessageInitShape<typeof RunCronNowRequestSchema>): Promise<RpcResult<void>> {
  try {
      await scheduleClient.runNow(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function validatePipeline(args: MessageInitShape<typeof ValidatePipelineRequestSchema>): Promise<RpcResult<ValidatePipelineResultPb>> {
  try {
      const response = await scheduleClient.validatePipeline(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export const listCronJobs = listCron;
export const scheduleTask = scheduleCron;
export const scheduleCronJob = scheduleCron;
export const cancelCronJob = cancelCron;
export const updateCronJob = updateCron;
export const runCronJobNow = runNow;
export const getCronLogs = getLogs;
export const clearCronLogs = clearLogs;
export const consumeCronNotifications = consumeNotifications;
