// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / SecretService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  ModuleSecretEntryPb,
  SecretDeleteUserRequestSchema,
  SecretGetSystemRequestSchema,
  SecretGetUserRequestSchema,
  SecretService,
  SecretSetSystemRequestSchema,
  SecretSetUserRequestSchema,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';
import { unBigInt } from './_unbigint';

const secretClient = createClient(SecretService, transport);

export async function listUser(): Promise<RpcResult<string[]>> {
  try {
      const response = await secretClient.listUser({});
      return { ok: true, data: unBigInt(response.names) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setUser(args: MessageInitShape<typeof SecretSetUserRequestSchema>): Promise<RpcResult<void>> {
  try {
      await secretClient.setUser(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getUser(args: MessageInitShape<typeof SecretGetUserRequestSchema>): Promise<RpcResult<string | null>> {
  try {
      const response = await secretClient.getUser(args ?? {});
      return { ok: true, data: response.present ? unBigInt(response.value) : null };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteUser(args: MessageInitShape<typeof SecretDeleteUserRequestSchema>): Promise<RpcResult<void>> {
  try {
      await secretClient.deleteUser(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listUserModuleSecrets(): Promise<RpcResult<ModuleSecretEntryPb[]>> {
  try {
      const response = await secretClient.listUserModuleSecrets({});
      return { ok: true, data: unBigInt(response.entries) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getSystem(args: MessageInitShape<typeof SecretGetSystemRequestSchema>): Promise<RpcResult<string | null>> {
  try {
      const response = await secretClient.getSystem(args ?? {});
      return { ok: true, data: response.present ? unBigInt(response.value) : null };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setSystem(args: MessageInitShape<typeof SecretSetSystemRequestSchema>): Promise<RpcResult<void>> {
  try {
      await secretClient.setSystem(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export const listUserSecrets = listUser;
export const setUserSecret = setUser;
export const getUserSecret = getUser;
export const deleteUserSecret = deleteUser;
export const getVertexKey = getSystem;
export const setVertexKey = setSystem;
export const getGeminiKey = getSystem;
export const setGeminiKey = setSystem;
