// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / SettingsService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  AiAssistantModelPb,
  AvailableAiModelPb,
  SettingsService,
  SettingsSetAiAssistantModelRequestSchema,
  SettingsSetAiModelRequestSchema,
  SettingsSetAiThinkingLevelRequestSchema,
  SettingsSetAnthropicCacheEnabledRequestSchema,
  SettingsSetLastModelByCategoryRequestSchema,
  SettingsSetTimezoneRequestSchema,
  SettingsSetUserPromptRequestSchema,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const settingsClient = createClient(SettingsService, transport);

export async function getTimezone(): Promise<RpcResult<string>> {
  try {
      const response = await settingsClient.getTimezone({});
      return { ok: true, data: response.timezone };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setTimezone(args: MessageInitShape<typeof SettingsSetTimezoneRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await settingsClient.setTimezone(args ?? {});
      return { ok: true, data: response.ok };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getAiModel(): Promise<RpcResult<string>> {
  try {
      const response = await settingsClient.getAiModel({});
      return { ok: true, data: response.model };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setAiModel(args: MessageInitShape<typeof SettingsSetAiModelRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await settingsClient.setAiModel(args ?? {});
      return { ok: true, data: response.ok };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getAiThinkingLevel(): Promise<RpcResult<string>> {
  try {
      const response = await settingsClient.getAiThinkingLevel({});
      return { ok: true, data: response.level };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setAiThinkingLevel(args: MessageInitShape<typeof SettingsSetAiThinkingLevelRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await settingsClient.setAiThinkingLevel(args ?? {});
      return { ok: true, data: response.ok };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getUserPrompt(): Promise<RpcResult<string>> {
  try {
      const response = await settingsClient.getUserPrompt({});
      return { ok: true, data: response.prompt };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setUserPrompt(args: MessageInitShape<typeof SettingsSetUserPromptRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await settingsClient.setUserPrompt(args ?? {});
      return { ok: true, data: response.ok };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getAnthropicCacheEnabled(): Promise<RpcResult<boolean>> {
  try {
      const response = await settingsClient.getAnthropicCacheEnabled({});
      return { ok: true, data: response.enabled };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setAnthropicCacheEnabled(args: MessageInitShape<typeof SettingsSetAnthropicCacheEnabledRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await settingsClient.setAnthropicCacheEnabled(args ?? {});
      return { ok: true, data: response.ok };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getLastModelByCategory(): Promise<RpcResult<unknown>> {
  try {
      const response = await settingsClient.getLastModelByCategory({});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setLastModelByCategory(args: MessageInitShape<typeof SettingsSetLastModelByCategoryRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await settingsClient.setLastModelByCategory(args ?? {});
      return { ok: true, data: response.ok };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getAiAssistantModel(): Promise<RpcResult<string>> {
  try {
      const response = await settingsClient.getAiAssistantModel({});
      return { ok: true, data: response.model };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setAiAssistantModel(args: MessageInitShape<typeof SettingsSetAiAssistantModelRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await settingsClient.setAiAssistantModel(args ?? {});
      return { ok: true, data: response.ok };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getAiAssistantDefault(): Promise<RpcResult<string>> {
  try {
      const response = await settingsClient.getAiAssistantDefault({});
      return { ok: true, data: response.model };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getAvailableAiAssistantModels(): Promise<RpcResult<AiAssistantModelPb[]>> {
  try {
      const response = await settingsClient.getAvailableAiAssistantModels({});
      return { ok: true, data: response.models };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getAvailableAiModels(): Promise<RpcResult<AvailableAiModelPb[]>> {
  try {
      const response = await settingsClient.getAvailableAiModels({});
      return { ok: true, data: response.models };
  } catch (err) {
    return toRpcError(err);
  }
}

