// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / SkillService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  SkillDeleteFileRequestSchema,
  SkillListFilesRequestSchema,
  SkillReadFileRequestSchema,
  SkillSaveFileRequestSchema,
  SkillService,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';
import { unBigInt } from './_unbigint';

const skillClient = createClient(SkillService, transport);

export async function listFiles(args: MessageInitShape<typeof SkillListFilesRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await skillClient.listFiles(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function readFile(args: MessageInitShape<typeof SkillReadFileRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await skillClient.readFile(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function saveFile(args: MessageInitShape<typeof SkillSaveFileRequestSchema>): Promise<RpcResult<void>> {
  try {
      await skillClient.saveFile(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteFile(args: MessageInitShape<typeof SkillDeleteFileRequestSchema>): Promise<RpcResult<void>> {
  try {
      await skillClient.deleteFile(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}
