// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / StatusService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  StatusCompleteRequestSchema,
  StatusFailRequestSchema,
  StatusGetRequestSchema,
  StatusListRequestSchema,
  StatusService,
  StatusStartRequestSchema,
  StatusUpdateRequestSchema,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';
import { unBigInt } from './_unbigint';

const statusClient = createClient(StatusService, transport);

export async function start(args: MessageInitShape<typeof StatusStartRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.start(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function update(args: MessageInitShape<typeof StatusUpdateRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.update(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function complete(args: MessageInitShape<typeof StatusCompleteRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.complete(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function fail(args: MessageInitShape<typeof StatusFailRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.fail(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function get(args: MessageInitShape<typeof StatusGetRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.get(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function list(args: MessageInitShape<typeof StatusListRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.list(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function stats(): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.stats({});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export const startJob = start;
export const updateJob = update;
export const completeJob = complete;
export const failJob = fail;
export const getJob = get;
export const listJobs = list;
export const getJobStats = stats;
