// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / StatusService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  StatusCompleteRequest,
  StatusFailRequest,
  StatusListRequest,
  StatusService,
  StatusStartRequest,
  StatusUpdateRequest,
  StringRequest,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const statusClient = createClient(StatusService, transport);

export async function start(args: StatusStartRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.start(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function update(args: StatusUpdateRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.update(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function complete(args: StatusCompleteRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.complete(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function fail(args: StatusFailRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.fail(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function get(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.get(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function list(args: StatusListRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.list(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function stats(): Promise<RpcResult<unknown>> {
  try {
      const response = await statusClient.stats({});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export const startJob = start;
export const updateJob = update;
export const completeJob = complete;
export const failJob = fail;
export const getJob = get;
export const listJobs = list;
export const getJobStats = stats;
