// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / StorageService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  StorageGlobFilesRequest,
  StorageService,
  StorageWriteFileRequest,
  StringRequest,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const storageClient = createClient(StorageService, transport);

export async function readFile(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await storageClient.readFile(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function readFileBinary(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await storageClient.readFileBinary(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function writeFile(args: StorageWriteFileRequest): Promise<RpcResult<void>> {
  try {
      await storageClient.writeFile(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteFile(args: StringRequest): Promise<RpcResult<void>> {
  try {
      await storageClient.deleteFile(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listDir(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await storageClient.listDir(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function listFiles(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await storageClient.listFiles(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getFileTree(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await storageClient.getFileTree(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function globFiles(args: StorageGlobFilesRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await storageClient.globFiles(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export const appendFile = writeFile;
