// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / TaskService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  PipelineResultPb,
  TaskRunRequest,
  TaskService,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const taskClient = createClient(TaskService, transport);

export async function run(args: TaskRunRequest): Promise<RpcResult<PipelineResultPb>> {
  try {
      const response = await taskClient.run(args ?? {});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export const runTask = run;
