// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / TelegramService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  StringRequest,
  TelegramProcessMessageRequest,
  TelegramService,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const telegramClient = createClient(TelegramService, transport);

export async function setupWebhook(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await telegramClient.setupWebhook(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function removeWebhook(): Promise<RpcResult<unknown>> {
  try {
      const response = await telegramClient.removeWebhook({});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getWebhookStatus(): Promise<RpcResult<unknown>> {
  try {
      const response = await telegramClient.getWebhookStatus({});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function isOwner(args: StringRequest): Promise<RpcResult<boolean>> {
  try {
      const response = await telegramClient.isOwner(args ?? {});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getWebhookSecret(): Promise<RpcResult<unknown>> {
  try {
      const response = await telegramClient.getWebhookSecret({});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function processMessage(args: TelegramProcessMessageRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await telegramClient.processMessage(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export const setupTelegramWebhook = setupWebhook;
export const removeTelegramWebhook = removeWebhook;
export const getTelegramWebhookStatus = getWebhookStatus;
export const isTelegramOwner = isOwner;
export const getTelegramWebhookSecret = getWebhookSecret;
export const processTelegramMessage = processMessage;
