// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / TemplateService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  StringRequest,
  TemplateSaveRequest,
  TemplateService,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const templateClient = createClient(TemplateService, transport);

export async function list(): Promise<RpcResult<unknown>> {
  try {
      const response = await templateClient.list({});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function get(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await templateClient.get(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function save(args: TemplateSaveRequest): Promise<RpcResult<void>> {
  try {
      await templateClient.save(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function deleteTemplate(args: StringRequest): Promise<RpcResult<void>> {
  try {
      await templateClient.delete(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export const listTemplates = list;
export const getTemplate = get;
export const saveTemplate = save;
