// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / ToolService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  StringRequestSchema,
  ToolBuildAiDefinitionsRequestSchema,
  ToolBuildMcpDescriptionsRequestSchema,
  ToolExecuteRequestSchema,
  ToolListRequestSchema,
  ToolRegisterManyRequestSchema,
  ToolRegisterRequestSchema,
  ToolService,
  ToolSetActivePlanStateRequestSchema,
  ToolStatsPb,
} from '../proto-gen/firebat_pb';
import { type MessageInitShape } from '@bufbuild/protobuf';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const toolClient = createClient(ToolService, transport);

export async function register(args: MessageInitShape<typeof ToolRegisterRequestSchema>): Promise<RpcResult<void>> {
  try {
      await toolClient.register(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function registerMany(args: MessageInitShape<typeof ToolRegisterManyRequestSchema>): Promise<RpcResult<void>> {
  try {
      await toolClient.registerMany(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function unregister(args: MessageInitShape<typeof StringRequestSchema>): Promise<RpcResult<boolean>> {
  try {
      const response = await toolClient.unregister(args ?? {});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getDefinition(args: MessageInitShape<typeof StringRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await toolClient.getDefinition(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function list(args: MessageInitShape<typeof ToolListRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await toolClient.list(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function execute(args: MessageInitShape<typeof ToolExecuteRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await toolClient.execute(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function buildAiDefinitions(args: MessageInitShape<typeof ToolBuildAiDefinitionsRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await toolClient.buildAiDefinitions(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function buildMcpDescriptions(args: MessageInitShape<typeof ToolBuildMcpDescriptionsRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await toolClient.buildMcpDescriptions(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getStats(): Promise<RpcResult<ToolStatsPb>> {
  try {
      const response = await toolClient.getStats({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getActivePlanState(args: MessageInitShape<typeof StringRequestSchema>): Promise<RpcResult<unknown>> {
  try {
      const response = await toolClient.getActivePlanState(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setActivePlanState(args: MessageInitShape<typeof ToolSetActivePlanStateRequestSchema>): Promise<RpcResult<void>> {
  try {
      await toolClient.setActivePlanState(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function clearActivePlanState(args: MessageInitShape<typeof StringRequestSchema>): Promise<RpcResult<void>> {
  try {
      await toolClient.clearActivePlanState(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export const registerTool = register;
export const registerToolsMany = registerMany;
export const unregisterTool = unregister;
export const getToolDefinition = getDefinition;
export const listTools = list;
export const executeTool = execute;
export const buildAiToolDefinitions = buildAiDefinitions;
export const buildMcpToolDescriptions = buildMcpDescriptions;
export const getToolStats = getStats;
