// AUTO-GENERATED by scripts/gen-api-client.mjs — DO NOT EDIT.
// Source: proto/firebat.proto / ToolService
//
// 새 RPC 추가: 1) proto/firebat.proto 수정 2) npm run gen:proto 3) npm run gen:api
// alias 추가: proto/adapter-overrides.json 의 aliases 영역

import {
  StringRequest,
  ToolBuildAiDefinitionsRequest,
  ToolBuildMcpDescriptionsRequest,
  ToolExecuteRequest,
  ToolListRequest,
  ToolRegisterManyRequest,
  ToolRegisterRequest,
  ToolService,
  ToolSetActivePlanStateRequest,
  ToolStatsPb,
} from '../proto-gen/firebat_pb';
import { transport } from './_transport';
import { createClient } from '@connectrpc/connect';
import { type RpcResult, toRpcError } from './types';

const toolClient = createClient(ToolService, transport);

export async function register(args: ToolRegisterRequest): Promise<RpcResult<void>> {
  try {
      await toolClient.register(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function registerMany(args: ToolRegisterManyRequest): Promise<RpcResult<void>> {
  try {
      await toolClient.registerMany(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function unregister(args: StringRequest): Promise<RpcResult<boolean>> {
  try {
      const response = await toolClient.unregister(args ?? {});
      return { ok: true, data: response.value };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getDefinition(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await toolClient.getDefinition(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function list(args: ToolListRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await toolClient.list(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function execute(args: ToolExecuteRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await toolClient.execute(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function buildAiDefinitions(args: ToolBuildAiDefinitionsRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await toolClient.buildAiDefinitions(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function buildMcpDescriptions(args: ToolBuildMcpDescriptionsRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await toolClient.buildMcpDescriptions(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getStats(): Promise<RpcResult<ToolStatsPb>> {
  try {
      const response = await toolClient.getStats({});
      return { ok: true, data: response };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function getActivePlanState(args: StringRequest): Promise<RpcResult<unknown>> {
  try {
      const response = await toolClient.getActivePlanState(args ?? {});
      return { ok: true, data: JSON.parse(response.rawJson) };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function setActivePlanState(args: ToolSetActivePlanStateRequest): Promise<RpcResult<void>> {
  try {
      await toolClient.setActivePlanState(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export async function clearActivePlanState(args: StringRequest): Promise<RpcResult<void>> {
  try {
      await toolClient.clearActivePlanState(args ?? {});
      return { ok: true, data: undefined };
  } catch (err) {
    return toRpcError(err);
  }
}

export const registerTool = register;
export const registerToolsMany = registerMany;
export const unregisterTool = unregister;
export const getToolDefinition = getDefinition;
export const listTools = list;
export const executeTool = execute;
export const buildAiToolDefinitions = buildAiDefinitions;
export const buildMcpToolDescriptions = buildMcpDescriptions;
export const getToolStats = getStats;
